
project_id = "xfwtjndfclckgvpvgiaj"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]

[functions.admin-users]
verify_jwt = false

[functions.deduct-credits]
verify_jwt = false

[functions.get-encryption-key]
verify_jwt = false

[functions.mpesa-callback]
verify_jwt = false

[functions.mspace-accounts]
verify_jwt = false

[functions.mspace-ussd-webhook]
verify_jwt = false

[functions.secure-admin-users]
verify_jwt = false

[functions.analytics-processor]
verify_jwt = false

[functions.metrics-collector]
verify_jwt = false

[functions.webhook-processor]
verify_jwt = false

[functions.webhook-test]
verify_jwt = false

[functions.user-segmentation]
verify_jwt = false
