// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmhxcwaaujznyogxmabq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtaHhjd2FhdWp6bnlvZ3htYWJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNTc5MzMsImV4cCI6MjA2MzkzMzkzM30.spxB2_8eyK_xofEr-Gyp8kdT-XurbBpdPFXpwlRw7C0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);